### ISSUE TITLE
Error on pub get

### ISSUE THREAD

**Issue by montyr75** [simon-void/pikaday_datepicker_angular#1]
When adding your package to my project and running `pub get`, I get:

```
Error on line 1, column 1 of https://pub.dartlang.org/api/packages/pikaday_datepicker_angular: Error loading transformer "dart_to_js_script_rewriter": package "dart_to_js_script_rewriter" is not a dependency.
```

Not sure what that's about. The date picker does still work (though not inside of a <material-popup>, but that's another issue).

**Comment by simon-void** [comment]
i guess i should comment line 24 in [pikaday_datepicker_angualar's pubspec-file](https://github.com/simon-void/pikaday_datepicker_angular/blob/master/pubspec.yaml)
I will do so shortly (within the next 30 minutes).
By the way, Google's Material Design Lite lib for Dart has since yesterday its own [Date- and Time-Picker](https://plus.google.com/+MikeMitterer/posts/FiewSrg47Gr) 
(I mainly created pikaday_datepicker_angular because Material Design Lite didn't have a timepicker at that point. That being said, there's nothing wrong with continuing to use my project :) )

**Comment by simon-void** [comment]
please try [version 3.0.1](https://pub.dartlang.org/packages/pikaday_datepicker_angular) which i just published.

**Comment by montyr75** [comment]
Excellent. That seems to have done the trick. Thanks for your work on this project, by the way.
